moduledir '/etc/puppet/modules'

mod 'puppetlabs/concat', '2.2.1'
mod 'puppetlabs/stdlib', '4.16.0'
mod 'puppetlabs/mysql', '3.10.0'
mod 'puppetlabs/apt', '2.4.0'
mod 'puppet/php', '5.0.0'
mod 'puppet-nginx', '0.6.0'
mod 'rafaelfc/pear', '1.0.3'
mod 'omegaup', :git => 'https://github.com/omegaup/puppet'
