moduledir '/usr/share/puppet/modules'

mod 'puppet-archive', '3.2.1'
mod 'puppet-nginx', '0.15.0'
mod 'puppet-php', '6.0.2'
mod 'puppet-zypprepo', '2.2.2'
mod 'puppet-cron', '1.3.1'
mod 'puppetlabs-apt', '6.2.1'
mod 'puppetlabs-concat', '5.1.0'
mod 'puppetlabs-docker', '3.8.0'
mod 'puppetlabs-inifile', '2.4.0'
mod 'puppetlabs-mysql', '7.0.0'
mod 'puppetlabs-stdlib', '5.1.0'
mod 'puppetlabs-translate', '1.2.0'
mod 'omegaup', :git => 'https://github.com/omegaup/puppet'
